[package]
name = "injoint-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
tokio = { version = "1.0", features = ["full"] }
syn = { version = "2.0.0", features = ["full"] }
quote = "1.0.38"
paste = "1.0.15"
proc-macro2 = "1.0.93"